import { expect, test } from '@playwright/test'

test('Third Order renders headers and selects matrix cells', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/play-to')
  const pane = page.locator('[data-role="to-pane"]')
  await expect(pane.locator('[data-role="to-cell"]')).toHaveCount(136)
  const previews = pane.locator('th img')
  await expect(previews).toHaveCount(25)
  await expect(previews.last()).toHaveAttribute('src', /^blob:/)
  const cells = pane.locator('[data-role="to-cell-preview"]')
  await expect(cells).toHaveCount(136, { timeout: 15000 })
  await pane.screenshot({ path: testInfo.outputPath('third-order-desktop.png') })
  const before = await previews.first().getAttribute('src')
  await pane.getByRole('combobox', { name: 'Hand', exact: true }).selectOption('spin')
  await expect(previews.first()).not.toHaveAttribute('src', before!)
  await expect(cells).toHaveCount(0)
  await pane.locator('[data-role="to-cell"][data-hand-ratio="1:3"][data-prop-ratio="1:7"]').click()
  await pane.locator('[data-role="to-column-header"][data-ratio="2:1"]').click()
  await expect(pane.locator('[data-role="to-cell"][aria-pressed="true"]')).toHaveAttribute(
    'data-prop-ratio',
    '1:7',
  )
  await pane.getByRole('combobox', { name: 'Hand', exact: true }).selectOption('anti')
  await expect(cells).toHaveCount(136, { timeout: 15000 })
  await expect.poll(() => new URL(page.url()).searchParams.has('r')).toBe(true)
  const firstVersionUrl = page.url()
  await pane.getByRole('combobox', { name: 'Version', exact: true }).selectOption('2')
  await expect.poll(() => page.url()).not.toBe(firstVersionUrl)
  await pane.getByRole('combobox', { name: 'Prop', exact: true }).selectOption('spin')
  await expect(cells).toHaveCount(0)
  const unsupportedUrl = page.url()
  await pane.locator('[data-role="to-cell"]').first().click()
  expect(page.url()).toBe(unsupportedUrl)
  await pane.getByRole('combobox', { name: 'Prop', exact: true }).selectOption('anti')
  await pane.locator('[data-role="to-customize-toggle"]').click()
  const previousColor = await previews.first().getAttribute('src')
  await pane.locator('[data-role="to-left-color"]').selectOption('Red')
  await expect(previews.first()).not.toHaveAttribute('src', previousColor!)
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(pane.locator('[data-role="to-shuffle"]')).toBeVisible()
  expect(errors).toEqual([])
})
